### ISSUE TITLE
weryfikacja słów

### ISSUE THREAD

**Issue by sebkaz** [katarzynakowalczyk950/Magisterka#1]
proszę sprawdzić jak będą wyglądać najczęsciej występujące słowa ale z usunięciem obecnie najczęściej pojawiających się słów "i" "you" - wybrać wszystkie które są powatarzające się niezależenie od rodzaju.

**Comment by katarzynakowalczyk950** [comment]
Dodałam linijkę do pliku Wstępna_analiza:
![image](https://github.com/katarzynakowalczyk950/Magisterka/assets/61494409/2eaee969-b126-43a1-b1c7-ebdf0f8c4be2)

**Comment by sebkaz** [comment]
ok. chodzi mi o procesowanie dalej, czyli sprawdzenie tego słownika od końca. początkowe najczęściej występujące słowa to raczej stop words - proszę też zobaczyć jakieś NLP analizy i zobaczyć co tam się robi do wygenerowania słowników i częstości słów.

A czy my chcemy generować muzykę ? czy teksty ?

**Comment by sebkaz** [comment]
exit
